title: Anish Miryala
description: Computer Engineer specializing in VLSI, ASIC Design, Digital Hardware, and Computer Architecture
url: "https://wickedstereo.github.io"
baseurl: "/Portfolio"
theme: null
plugins:
  - jekyll-feed
# Optional: Add your Google Analytics tracking ID (Format: G-XXXXXXXXXX or UA-XXXXXXXXX-X)
# google_analytics: ""
